// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChdEhSuXhFNmVw-pHWcy75495XOVEDjaU',
    appId: '1:927104246158:web:a905106ec91f040a7a84df',
    messagingSenderId: '927104246158',
    projectId: 'liverpool-622e1',
    authDomain: 'liverpool-622e1.firebaseapp.com',
    storageBucket: 'liverpool-622e1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClPQJU8GNmF_fbpujkaLDQ05XS2Wh4cJg',
    appId: '1:927104246158:android:4a2d89d5e91c7ac47a84df',
    messagingSenderId: '927104246158',
    projectId: 'liverpool-622e1',
    storageBucket: 'liverpool-622e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDCyc7Bf2uiz6Te6wo6_oNlc09YnJAT5o',
    appId: '1:927104246158:ios:b8ae978acc43b84c7a84df',
    messagingSenderId: '927104246158',
    projectId: 'liverpool-622e1',
    storageBucket: 'liverpool-622e1.appspot.com',
    androidClientId: '927104246158-2fmbfki5rsmihj9b9pstpou2d3hd9led.apps.googleusercontent.com',
    iosClientId: '927104246158-uvefgl2pmt2371behvs4itj4drtgd019.apps.googleusercontent.com',
    iosBundleId: 'com.example.liverpool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDCyc7Bf2uiz6Te6wo6_oNlc09YnJAT5o',
    appId: '1:927104246158:ios:b0315d09e6f27e5b7a84df',
    messagingSenderId: '927104246158',
    projectId: 'liverpool-622e1',
    storageBucket: 'liverpool-622e1.appspot.com',
    androidClientId: '927104246158-2fmbfki5rsmihj9b9pstpou2d3hd9led.apps.googleusercontent.com',
    iosClientId: '927104246158-1hg4s8bc3dgvbvk2ut7sm4aoq7fp0jee.apps.googleusercontent.com',
    iosBundleId: 'com.example.liverpool.RunnerTests',
  );
}
